apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: inventory-api
    newName: harbor.dev.test/library/inventory-api
    newTag: v1

# DEV 환경은 파드 2개
replicas:
  - name: inventory-api
    count: 2
