apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-api-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sc7258/k8s-apps.git'
    targetRevision: main
    path: inventory-api/k8s/overlays/qa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: inventory-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
