apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproute.yaml
  - httproute-domain.yaml

images:
  - name: inventory-api
    newName: harbor.local.test/library/inventory-api
    newTag: v999.9.9

# 필요한 경우 로컬 환경에만 적용할 설정(예: Replicas 1개)
replicas:
  - name: inventory-api
    count: 1
