spring:
  application:
    name: inventory-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/inventory_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
    url: /docs/api/v1/inventory-api.yaml
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
